/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import Main.controlador.Controlador;
import javax.swing.ImageIcon;


public class Pantalla extends javax.swing.JFrame{

    private final Controlador m = new Controlador();
 
    public Pantalla() {
        initComponents();
        this.whoWin.setText("-");
        this.setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        piedra = new javax.swing.JButton();
        papel = new javax.swing.JButton();
        tijera = new javax.swing.JButton();
        namePlayer = new javax.swing.JLabel();
        scorePlayer = new javax.swing.JLabel();
        nameComputer = new javax.swing.JLabel();
        scoreComputer = new javax.swing.JLabel();
        whoWin = new javax.swing.JLabel();
        sacaComputer = new javax.swing.JLabel();
        sacaPlayer = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        fondoLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(943, 506));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        piedra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/piedra.png"))); // NOI18N
        piedra.setMaximumSize(new java.awt.Dimension(64, 64));
        piedra.setMinimumSize(new java.awt.Dimension(64, 64));
        piedra.setPreferredSize(new java.awt.Dimension(64, 64));
        piedra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                piedraActionPerformed(evt);
            }
        });
        getContentPane().add(piedra, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 100, 80));

        papel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/papel.png"))); // NOI18N
        papel.setMaximumSize(new java.awt.Dimension(64, 64));
        papel.setMinimumSize(new java.awt.Dimension(64, 64));
        papel.setPreferredSize(new java.awt.Dimension(64, 64));
        papel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                papelActionPerformed(evt);
            }
        });
        getContentPane().add(papel, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 370, 90, 80));

        tijera.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/tijera.png"))); // NOI18N
        tijera.setMaximumSize(new java.awt.Dimension(64, 64));
        tijera.setMinimumSize(new java.awt.Dimension(64, 64));
        tijera.setPreferredSize(new java.awt.Dimension(64, 64));
        tijera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tijeraActionPerformed(evt);
            }
        });
        getContentPane().add(tijera, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 370, 90, 80));

        namePlayer.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        namePlayer.setForeground(new java.awt.Color(255, 255, 255));
        namePlayer.setText("Jugador");
        getContentPane().add(namePlayer, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        scorePlayer.setBackground(new java.awt.Color(255, 255, 255));
        scorePlayer.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        scorePlayer.setForeground(new java.awt.Color(255, 255, 255));
        scorePlayer.setText("0");
        getContentPane().add(scorePlayer, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 50, -1));

        nameComputer.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        nameComputer.setForeground(new java.awt.Color(255, 255, 255));
        nameComputer.setText("Computadora");
        getContentPane().add(nameComputer, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 10, -1, -1));

        scoreComputer.setBackground(new java.awt.Color(255, 255, 255));
        scoreComputer.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        scoreComputer.setForeground(new java.awt.Color(255, 255, 255));
        scoreComputer.setText("0");
        getContentPane().add(scoreComputer, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 30, 30, 30));

        whoWin.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        whoWin.setForeground(new java.awt.Color(255, 255, 255));
        whoWin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(whoWin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 940, 40));
        getContentPane().add(sacaComputer, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 160, -1, -1));
        getContentPane().add(sacaPlayer, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, -1, -1));

        jLabel1.setText("Juega piedra papel y tijeras");
        jPanel1.add(jLabel1);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 110, 210, 40));

        fondoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/fondo.png"))); // NOI18N
        getContentPane().add(fondoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void piedraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_piedraActionPerformed

       int valorMaquina = m.turnoMaquina();

       this.sacaPlayer.setIcon(m.traductorTurnero(0));
       this.sacaPlayer.repaint();
   
       this.sacaComputer.setIcon(m.traductorTurnero(valorMaquina));
       this.sacaComputer.repaint();
      
       String Ganador = m.versus(0, valorMaquina);
       this.whoWin.setText(Ganador);
       m.contadorDeVictorias(Ganador);
    
       this.scoreComputer.setText(Integer.toString(m.getGanaComputer()));
       this.scorePlayer.setText(Integer.toString(m.getGanaPlayer()));
    }//GEN-LAST:event_piedraActionPerformed

    private void papelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_papelActionPerformed
    
       int valorMaquina = m.turnoMaquina();
     
       this.sacaPlayer.setIcon(m.traductorTurnero(1));
       this.sacaPlayer.repaint();
       
       this.sacaComputer.setIcon(m.traductorTurnero(valorMaquina));
       this.sacaComputer.repaint();
     
       String Ganador = m.versus(1, valorMaquina);
       this.whoWin.setText(Ganador);
       m.contadorDeVictorias(Ganador);
    
       this.scoreComputer.setText(Integer.toString(m.getGanaComputer()));
       this.scorePlayer.setText(Integer.toString(m.getGanaPlayer()));
    }//GEN-LAST:event_papelActionPerformed

    private void tijeraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tijeraActionPerformed
      
       int valorMaquina = m.turnoMaquina();
       
       this.sacaPlayer.setIcon(m.traductorTurnero(2));
       this.sacaPlayer.repaint();
       
       this.sacaComputer.setIcon(m.traductorTurnero(valorMaquina));
       this.sacaComputer.repaint();
       
       String Ganador = m.versus(2, valorMaquina);
       this.whoWin.setText(Ganador);
       m.contadorDeVictorias(Ganador);
     
       this.scoreComputer.setText(Integer.toString(m.getGanaComputer()));
       this.scorePlayer.setText(Integer.toString(m.getGanaPlayer()));
    }//GEN-LAST:event_tijeraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pantalla().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel fondoLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel nameComputer;
    private javax.swing.JLabel namePlayer;
    private javax.swing.JButton papel;
    private javax.swing.JButton piedra;
    private javax.swing.JLabel sacaComputer;
    private javax.swing.JLabel sacaPlayer;
    private javax.swing.JLabel scoreComputer;
    private javax.swing.JLabel scorePlayer;
    private javax.swing.JButton tijera;
    private javax.swing.JLabel whoWin;
    // End of variables declaration//GEN-END:variables
}
